name: ci

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/checkout@v4
        with:
          node-version: 18

      - name: Force Failure
        run: (exit 1)
